version: "3.8"

services:
  backend:
    build: .
    container_name: backend_melon
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_melon
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: melon_project_melon
      MYSQL_USER: melon
      MYSQL_PASSWORD: doome972545
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
